server:
  secret_key: "change-me-in-production"
  bind_address: "0.0.0.0"
  port: 8888
  limiter: false
  image_proxy: false
  debug: false

ui:
  static_use_hash: true
  default_locale: en
  theme: simple

search:
  safe_search: 0
  autocomplete: ""
  language: en-US
  formats:
    - html
    - json

outgoing:
  request_timeout: 10.0
  max_request_timeout: 15.0
  useragent_suffix: "GeMUNi MUN Research"

enabled_plugins:
  - "Basic Calculator"
  - "Hostname replace"
  - "Open Access DOI rewrite"
  - "Tracker URL removal"

searchdd:
  safe_search: 0
  autocomplete: ""
