export const COUNTRIES = [
  'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda',
  'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
  'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin',
  'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei',
  'Bulgaria', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon',
  'Canada', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia',
  'Comoros', 'Congo', 'Costa Rica', "Côte d'Ivoire", 'Croatia', 'Cuba', 'Cyprus',
  'Czech Republic', 'Democratic Republic of the Congo', 'Denmark', 'Djibouti',
  'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador',
  'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Fiji',
  'Finland', 'France', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece',
  'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras',
  'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel',
  'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati',
  'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia',
  'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi',
  'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania',
  'Mauritius', 'Mexico', 'Micronesia', 'Moldova', 'Monaco', 'Mongolia',
  'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal',
  'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Korea',
  'North Macedonia', 'Norway', 'Oman', 'Pakistan', 'Palau', 'Palestine', 'Panama',
  'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal',
  'Qatar', 'Romania', 'Russia', 'Rwanda', 'Saint Kitts and Nevis', 'Saint Lucia',
  'Saint Vincent and the Grenadines', 'Samoa', 'San Marino', 'Sao Tome and Principe',
  'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore',
  'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa',
  'South Korea', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname',
  'Sweden', 'Switzerland', 'Syria', 'Tajikistan', 'Tanzania', 'Thailand',
  'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey',
  'Turkmenistan', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates',
  'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan', 'Vanuatu',
  'Vatican City', 'Venezuela', 'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe',
] as const

export const COMMITTEES = [
  { value: 'UNGA', label: 'UN General Assembly', un: true },
  { value: 'UNHRC', label: 'UN Human Rights Council', un: true },
  { value: 'UNSC', label: 'UN Security Council', un: true },
  { value: 'WHO', label: 'World Health Organization', un: true },
  { value: 'ECOSOC', label: 'Economic and Social Council', un: true },
  { value: 'UN_WOMEN', label: 'UN Women', un: true },
  { value: 'UNEP', label: 'UN Environment Programme', un: true },
  { value: 'UNICEF', label: 'UN Children\'s Fund', un: true },
  { value: 'IAEA', label: 'International Atomic Energy Agency', un: true },
  { value: 'UNESCO', label: 'UN Educational, Scientific and Cultural Organization', un: true },
  { value: 'IMF', label: 'International Monetary Fund', un: true },
  { value: 'FAO', label: 'Food and Agriculture Organization', un: true },
] as const

export const REPORT_SECTIONS = [
  'executive_summary',
  'country_profile',
  'agenda_background',
  'current_situation',
  'country_position',
  'un_resolutions',
  'ngo_reports',
  'statistics',
  'bloc_positions',
  'speaking_points',
  'possible_solutions',
  'questions_to_ask',
  'images',
  'sources',
] as const

export const TRUSTED_SOURCES = [
  { domain: 'un.org', type: 'UN', priority: 1 },
  { domain: 'who.int', type: 'UN', priority: 1 },
  { domain: 'unicef.org', type: 'UN', priority: 1 },
  { domain: 'undp.org', type: 'UN', priority: 1 },
  { domain: 'unesco.org', type: 'UN', priority: 1 },
  { domain: 'unhcr.org', type: 'UN', priority: 1 },
  { domain: 'fao.org', type: 'UN', priority: 1 },
  { domain: 'amnesty.org', type: 'NGO', priority: 2 },
  { domain: 'hrw.org', type: 'NGO', priority: 2 },
  { domain: 'crisisgroup.org', type: 'NGO', priority: 2 },
  { domain: 'worldbank.org', type: 'IO', priority: 2 },
  { domain: 'oecd.org', type: 'IO', priority: 2 },
  { domain: 'imf.org', type: 'IO', priority: 2 },
  { domain: 'icrc.org', type: 'NGO', priority: 2 },
  { domain: 'weforum.org', type: 'NGO', priority: 3 },
  { domain: 'sipri.org', type: 'Academic', priority: 3 },
  { domain: 'transparency.org', type: 'NGO', priority: 2 },
  { domain: 'brookings.edu', type: 'Academic', priority: 3 },
  { domain: 'chathamhouse.org', type: 'Academic', priority: 3 },
  { domain: 'cfr.org', type: 'Academic', priority: 3 },
] as const
